<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajax By Promise</title>
</head>

<body>
    <script>
        // 封装 ajax 请求：传入回调函数 success 和 fail
        function ajax(url, success) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.responseType = 'json';
            xmlhttp.open('GET', url);
            xmlhttp.send();
            xmlhttp.onreadystatechange = function () {
                if (xmlhttp.readyState === 4 && xmlhttp.status === 200) {
                    success && success(xmlhttp.response);}
                // } else {
                //     // 这里的 && 符号，意思是：如果传了 fail 参数，就调用后面的 fail()；如果没传 fail 参数，就不调用后面的内容。因为 fail 参数不一定会传。
                //     fail && fail(new Error('接口请求失败'));
                // }
            };
        }

        function promiseA() {
            return new Promise((resolve, reject) => {
                // 执行 ajax 请求
                // 这里代码是同步的
                ajax('http://localhost:8000/promise-server', (res) => {
                    // 这里的 res 是接口的返回结果。返回码 retCode 是动态数据。
                    if (res.retCode == 0) {
                        // 接口请求成功时调用
                        resolve('request success' + JSON.stringify(res));
                    } else {
                        // 接口请求失败时调用
                        reject({ retCode: -1, msg: 'network error' });
                    }
                });
            });
        }


        // 第二步：业务层的接口调用。这里的 data 就是 从 resolve 和 reject 传过来的，也就是从接口拿到的数据
        promiseA()
            .then((res) => {
                // 从 resolve 获取正常结果：接口请求成功后，打印接口的返回结果
                console.log(res);
            })
            .catch((err) => {
                // 从 reject 获取异常结果
                console.log(err);
            });


    </script>

</body>

</html>